# Generated by Django 4.2.3 on 2023-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_ads_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='car',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='ads',
            new_name='ad',
        ),
        migrations.AlterField(
            model_name='ads',
            name='main_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
